# Generated by Django 3.0.6 on 2020-06-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='traitement_content',
            field=models.FileField(upload_to=''),
        ),
    ]
