# Generated by Django 2.2.10 on 2020-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitement', '0002_auto_20200603_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='traitement_type',
            field=models.IntegerField(choices=[(1, 'ordonnance'), (2, 'massage')], default=1),
        ),
    ]
