# Generated by Django 2.2.10 on 2020-07-11 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traitement', '0003_auto_20200609_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='patient_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='traitement_type',
            field=models.IntegerField(choices=[(1, 'ordonnance'), (2, 'kinésithérapie'), (3, 'analyses')], default=1),
        ),
    ]
