# Generated by Django 2.2.10 on 2020-07-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitement', '0005_remove_traitement_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='traitement_content',
            field=models.ImageField(upload_to=''),
        ),
    ]
