# Generated by Django 2.2.10 on 2020-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitement', '0006_auto_20200711_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='traitement_content',
            field=models.FileField(upload_to=''),
        ),
    ]
