# Generated by Django 2.2.10 on 2020-07-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitement', '0007_auto_20200711_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='traitement_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
