# Generated by Django 2.2.10 on 2020-06-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='spec_doctor',
            field=models.CharField(choices=[('Médecin générale', 'Médecin générale'), (' Chirurgien', 'Chirurgie'), (' Dermatologue', 'Dermatologue'), (' Pédiatre', 'Pédiatre'), (' Cardiologue', 'Cardilogue')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Traitement',
        ),
    ]
