# Generated by Django 2.2.10 on 2020-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20200601_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='role_subscriber',
            field=models.IntegerField(choices=[(1, 'Patient'), (2, 'Doctor')], default=1),
        ),
    ]
